# Start with Maven image with JDK 17
FROM openjdk:17-slim AS builder

#Set env variables for Maven version
ENV MAVEN_VERSION=3.8.8
ENV MAVEN_HOME=/opt/maven
ENV PATH=$MAVEN_HOME/bin:$PATH

# Install Ansible
RUN  apt update && apt upgrade -y && apt install -y python3  \
    && apt install -y ansible
     

# Install Docker CLI and Maven
RUN apt update && apt install -y \
    curl \
    && curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -xz -C /opt && \
    ln -s /opt/apache-maven-$MAVEN_VERSION /opt/maven \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

FROM openjdk:17-slim AS FINAL

RUN apt-get update && apt upgrade -y && apt-get install -y \
    docker.io \
    curl \
    ca-certificates \
    git \
    && apt clean

COPY --from=builder /usr/local/lib/python3.*/ /usr/local/lib/python3.*/
COPY --from=builder /usr/local/bin/ansible* /usr/local/bin/
COPY --from=builder /root/.ansible /root/.ansible

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install kubectl (latest stable version)
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/

# Set working directory
WORKDIR /app

# Ensure Maven and Docker are available
RUN mvn -version && docker --version \
    && ansible --version && kubectl version --client && \
    az version

# Default command (can be overridden)
CMD ["bash"]

